export const SORTING_ACTIONS = {
  EARLY_FIRST: "EARLY_FIRST",
  LATELY_FIRST: "LATELY_FIRST",
  COMPLETED_FIRST: "COMPLETED_FIRST",
  UNCOMPLETED_FIRST: "UNCOMPLETED_FIRST",
  OVERDUE_FIRST: "OVERDUE_FIRST",
  HIGH_PRIORITY_FIRST: "HIGH_PRIORITY_FIRST",
  LOW_PRIORITY_FIRST: "LOW_PRIORITY_FIRST",
};
